<?php
/**
 * Created by PhpStorm.
 * user: trina
 * Date: 18-12-13
 * Time: 上午9:01
 */

namespace backend\models\search;

use backend\models\Role;
use yii\base\Model;
use yii\data\ActiveDataProvider;

class RoleSearch extends Role
{
    //验证规则
    public function rules()
    {
        return [
            [['id', 'status'], 'integer'],
            ['name', 'string', 'max' => 50],
            [['created_at', 'updated_at'], 'safe'],
        ]; // TODO: Change the autogenerated stub
    }

    //场景
    public function scenarios()
    {
        return Model::scenarios(); // TODO: Change the autogenerated stub
    }

    public function search($params)
    {
        $query = Role::find();

        //数据提供者，可分页和排序
        $dataProvider = new ActiveDataProvider([
            'query' => $query,
            'pagination' => [
                'pageSize' => 2,
            ],
            'sort' => [
                'defaultOrder' => [
                    'id' => SORT_DESC,
                ],
            ]
        ]);

        //加载数据，并验证
        $this->load($params);
        if (!$this->validate()) {
            return $dataProvider;
        }

        //过滤
        $query->andFilterWhere([
            'id' => $this->id,
            'status' => $this->status,
        ]);
        $query->andFilterWhere(['like', 'name', $this->name]);

        //时间过滤
        if ($this->created_at) {
            list($start, $end) = explode(' to ', $this->created_at);
            $end .= ' 23:59:59';
            $query->andFilterWhere(['and', ['>=', 'created_at', strtotime($start)], ['<=', 'created_at', $end]]);
        }
        if ($this->updated_at) {
            list($start, $end) = explode(' to ', $this->updated_at);
            $end .= ' 23:59:59';
            $query->andFilterWhere(['and', ['>=', 'updated_at', strtotime($start)], ['<=', 'updated_at', strtotime($end)]]);
        }

        return $dataProvider;
    }
}