<?php
/**
 * Created by PhpStorm.
 * user: trina
 * Date: 18-12-14
 * Time: 下午3:18
 */

namespace backend\models;

use phpDocumentor\Reflection\Types\Integer;
use yii\db\ActiveRecord;

/**
 * permission Model
 * @property integer $id
 * @property integer $fid
 * @property String $name
 * @property String $url
 * @property integer $sort
 * @property integer $created_at
 * @property integer $updated_at
 */
class Permission extends ActiveRecord
{
    const SHOW = 1;
    const DISPLAY = 0;

    //表名
    public static function tableName()
    {
        return 'permission';
    }

    //验证规则
    public function rules()
    {
        return [
            [['fid', 'sort', 'is_show', 'created_at', 'updated_at'], 'integer'],
            ['name', 'require'],
            [['fid', 'is_show'], 'default', 'value' => 0],
            ['is_show', 'in', 'range' => [self::SHOW, self::DISPLAY]],
            ['sort', 'default', 'value' => 99],
            ['name', 'string', 'max' => 100],
        ]; // TODO: Change the autogenerated stub
    }
}