<?php
/**
 * Created by PhpStorm.
 * user: trina
 * Date: 18-12-12
 * Time: 下午5:22
 */

namespace backend\models;

use yii\db\ActiveRecord;
use yii\web\NotFoundHttpException;

/**
 * Role Model
 *
 * @property integer $id
 * @property string $name
 * @property integer $status
 * @property integer $created_at
 * @property integer $updated_at
 */
class Role extends ActiveRecord
{
    const STATUS_DELETE = 0;
    const STATUS_ACTIVE = 10;

    /**
     * 表名
     */
    public static function tableName()
    {
        return 'role'; // TODO: Change the autogenerated stub
    }

    /**
     * 验证规则
     */
    public function rules()
    {
        return [
            ['name', 'string', 'max' => 50],
            [['name', 'created_at', 'updated_at'], 'required'],
            ['name', 'unique'],
            [['status', 'created_at', 'updated_at'], 'integer'],
            ['status', 'default', 'value' => self::STATUS_ACTIVE],
            ['status', 'in', 'range' => [self::STATUS_ACTIVE, self::STATUS_DELETE]],
        ]; // TODO: Change the autogenerated stub
    }

    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Name',
            'status' => 'Status'
        ]; // TODO: Change the autogenerated stub
    }

    /**
     * 根据id查找数据，且不存在抛错
     * @param $id
     * @return array|null|ActiveRecord
     * @throws NotFoundHttpException
     * user: trina
     */
    public function findModel($id)
    {
        $model = self::find()->where(['id' => $id])->one();
        if (!$model) {
            throw new NotFoundHttpException('The requested page does not exist.');
        }

        return $model;
    }
}