<?php
/**
 * Created by PhpStorm.
 * User: trina
 * Date: 18-9-14
 * Time: 上午9:44
 */

namespace backend\models;


use yii\base\Model;
use yii\web\UploadedFile;

class UploadForm extends Model
{
    /**
     * @var UploadedFile
     */
    public $imageFile;

    public function rules()
    {
        return [
            [['imageFile'], 'file', 'skipOnEmpty' => false, 'extensions' => 'png, jpg, jpeg']
        ]; // TODO: Change the autogenerated stub
    }

    public function upload()
    {
        if ($this->validate()) {
            $this->imageFile->saveAs(dirname(dirname(__DIR__)) . '/backend/web/uploads/' .$this->imageFile->baseName.'.'.$this->imageFile->extension);
            return true;
        }
        return false;
    }
}